CREATE TABLE NguoiDung
(
	IDNCC INT IDENTITY(1,1) PRIMARY KEY,
	HoVaTen NVARCHAR(70),
	QuyenHan VARCHAR(50)
)
GO

CREATE TABLE MonAn
(
	IDMA INT IDENTITY(1,1) PRIMARY KEY,
	TenMonAn NVARCHAR(70),
	HinhAnh TEXT,
	IDNCC INT REFERENCES  NguoiDung(IDNCC) 
)
GO