CREATE TABLE NguoiDung
(
	IDNCC INT PRIMARY KEY,
	HoVaTen NVARCHAR(50),
	QuyenHan NVARCHAR(20)
)

CREATE TABLE MonAn
(
	IDMA INT PRIMARY KEY,
	TenMonAn NVARCHAR(30),
	HinhAnh TEXT,
	IDNCC INT FOREIGN KEY REFERENCES NguoiDung(IDNCC)
)